# Trust policy for testing octo-sts-rust
# Used for testing the Cloudflare Workers STS deployment
#
# Usage in GitHub Actions:
#   Exchange OIDC token at https://octo-sts.liam-helmer-428.workers.dev/sts/exchange
#   with scope: Epiphytic/.github, identity: octo-sts-test

issuer: https://token.actions.githubusercontent.com

# Match workflows from the octo-sts-rust repository
subject_pattern: "^repo:Epiphytic/octo-sts-rust:.*$"

# Permissions for testing
permissions:
  # Read repository contents
  contents: read
  # Read workflow/actions status
  actions: read

# ALLOWED repositories - only these can be accessed
repositories:
  - octo-sts-rust
  - gear